### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by MiaoDX** [CopernicaMarketingSoftware/VARIANT-CPP#3]
Hi,
I was looking for python alike dictionary, this implement seems interesting (even though relay on json-c and not head-only). However, it seems that parsing vector as value is not supported.

``` cpp
    Variant::Value variant_d;
    std::vector<float> vec = std::vector<float>(1000000, 0);
    variant_d["vec"] = vec;
```
So, is this project still alive? and any suggestions?

**Comment by EmielBruijntjes** [comment]
We no longer maintain this project. The code does not even run in production.
